name: Secrets/Variablsの参照例
on:
  push:
  workflow_dispatch:

jobs:
  view:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v4
    - name: Variables(refer value)
      run: |
        # 特定の変数の値を参照する
        echo "Repository Variable 'FOOBAR': ${{ vars.FOOBAR }}"
    - name: Secrets(refer value)
      run: |
        # 特定のシークレットの値を参照する
        echo "Repository Secret 'FOOBAR': ${{ secrets.FOOBAR }}"
        